esphome:
  name: mum-night-light
  friendly_name: Night Light (Mum's)

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Night-Light Fallback Hotspot"
    password: !secret ap_password

captive_portal:

light:
  - platform: monochromatic
    name: "White LED"
    output: white_led_output
    restore_mode: ALWAYS_ON

output:
  - platform: ledc
    pin: GPIO4
    id: white_led_output

