---
#
# This gets added to configuration.yaml in Home Assistant.
#
#
# Defines a sensor that caluculates counts of toggles of the
# rain_gauge (zigbee door sensor)
#

sensor:
  - platform: history_stats
    unique_id: rain_gauge_flips_on
    name: "Rain Gauge flips/on"
    entity_id: binary_sensor.rain_gauge
    state: "on"
    type: count
    start: "{{ now() - timedelta(hours=24)}}"
    end: "{{ now() }}"
  - platform: history_stats
    unique_id: rain_gauge_flips_off
    name: "Rain Gauge flips/off"
    entity_id: binary_sensor.rain_gauge
    state: "off"
    type: count
    start: "{{ now() - timedelta(hours=24)}}"
    end: "{{ now() }}"
  - platform: history_stats
    unique_id: rain_gauge_flips_on_hour
    name: "Rain Gauge flips/on [hour]"
    entity_id: binary_sensor.rain_gauge
    state: "on"
    type: count
    start: "{{ now() - timedelta(hours=1)}}"
    end: "{{ now() }}"
  - platform: history_stats
    unique_id: rain_gauge_flips_off_hour
    name: "Rain Gauge flips/off [hour]"
    entity_id: binary_sensor.rain_gauge
    state: "off"
    type: count
    start: "{{ now() - timedelta(hours=1)}}"
    end: "{{ now() }}"

#
# Defines template sensors that use the flips caluculated above.
# Creates hourly and daily measurements.
#
#

#
# Note - we subtract 1 since the rain guage is alway in 1 of the states (on/off)
#        and we care only for a transition from one state to another, so a count
#        of 1 indicates no transistion, so we subtract the one and keep things sane.
#

template:

  - sensor:
      - name: Rainfall [day]
        state_class: measurement
        unique_id: rainfall_per_day
        unit_of_measurement: mm
        icon: mdi:weather-pouring
        state: >-
          {% set count = (states('sensor.rain_gauge_flips_on') | int(0)) +
                          (states('sensor.rain_gauge_flips_off') | int(0)) %}
          {% set count = count - 1 %}
          {% if count < 0 %}
          {%   set count = 0  %}
          {% endif %}
          {% set mm = count * 0.31569 %}
          {% if count >= 0 %}
            {{ mm|round(1, 'floor') }}
          {% endif %}
      - name: Rainfall per hour
        state_class: measurement
        unique_id: rainfall_per_hour
        unit_of_measurement: mm
        icon: mdi:weather-pouring
        state: >-
          {% set on = states('sensor.rain_gauge_flips_on_hour') | int(0) %}
          {% set off = states('sensor.rain_gauge_flips_off_hour') | int(0) %}
          {% set count = (on + off) - 1 %}
          {% if count < 0 %}
          {%   set count = 0  %}
          {% endif %}          
          {% set mm = count * 0.31569 %}
          {% if mm >= 0 %}
            {{ mm | round(1, 'floor') }}
          {% endif %}

